
import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'pt' | 'en' | 'es' | 'zh' | 'hi' | 'ar' | 'fr' | 'ru' | 'ja' | 'de';

export const LANGUAGES: { code: Language; name: string; nativeName: string; flag: string }[] = [
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷' },
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, any>> = {
  pt: {
    app_name: 'Dog Drive',
    landing_subtitle: 'Encontre o par perfeito para seu pet. Conecte-se com passeadores e novos amigos.',
    choose_lang: 'Escolha seu idioma',
    login_title: 'Bem-vindo de volta!',
    email_label: 'E-mail ou Usuário',
    password_label: 'Senha',
    forgot_pass: 'Esqueceu sua senha?',
    enter_btn: 'Entrar',
    or_continue: 'Ou continue com',
    no_account: 'Não tem uma conta?',
    signup_action: 'Cadastre-se',
    onboarding_title: 'Bem-vindo ao Dog Drive!',
    onboarding_sub: 'Selecione seu tipo de perfil para começar.',
    owner: 'Dono do Pet',
    walker: 'Passeador',
    boarding: 'Hospedagem',
    petshop: 'Petshop',
    grooming: 'Banho e Tosa',
    shop_function: 'Vender Produtos',
    email_placeholder: 'ex: amantedecao@email.com',
    password_placeholder: 'Digite sua senha',
    login_subtitle: 'O match perfeito para seu pet',
    continue: 'Continuar',
    match_tab: 'MATCH',
    services_tab: 'SERVIÇOS',
    chat_tab: 'CONVERSAS',
    help_tab: 'AJUDA',
    settings_title: 'Configurações',
    edit_profile: 'Editar Perfil',
    my_dogs: 'Meus Cães',
    add_another_dog: 'Adicionar outro cão',
    save_changes: 'Salvar Alterações',
    services_title: 'O que seu cão precisa?',
    walking_cat: 'Passeio',
    boarding_cat: 'Hospedagem',
    grooming_cat: 'Banho e Tosa',
    vet_cat: 'Veterinário',
    marketplace_cat: 'Mercado',
    find_walker: 'Encontrar Passeador',
    nearby: 'Próximos',
    top_rated: 'Melhor Avaliados',
    lowest_price: 'Menor Preço',
    per_hour: '/hr',
    book: 'Agendar',
    total: 'Total',
    messages: 'Mensagens',
    conversations: 'Conversas',
    need_help: 'Precisa de ajuda?',
    call_police: 'Chamar Polícia',
    report_accident: 'Reportar Acidente',
    get_started: 'Começar',
    select_language: 'Selecione o idioma',
    vet_clinic: 'Clínica Veterinária',
    grooming_shop: 'Banho e Tosa / Petshop',
    business_type_title: 'Tipo de Negócio',
    business_type_subtitle: 'Selecione o serviço que sua empresa oferece.',
    select_country: 'Selecione o País',
    brazil: 'Brasil',
    europe: 'Europa',
    business: 'Empresa',
    pet_name: 'Nome do Pet',
    pet_age: 'Idade do Pet',
    pet_photo: 'Foto do Pet',
    pet_traits: 'Traços do Pet',
    pet_request: 'O que você procura?',
    business_name: 'Nome da Empresa',
    tax_id_eu: 'NIF / VAT Number',
    business_address: 'Endereço Comercial',
    service_type: 'Tipos de Serviço',
    walking: 'Passeio',
    boarding_label: 'Hospedagem',
    doc_upload: 'Envio de Documento',
    address_label: 'Endereço',
    bank_title: 'Dados Bancários',
    pix_key: 'Chave PIX / IBAN',
    experience_label: 'Experiência / Bio',
    finish_btn: 'Finalizar',
  },
  en: {
    app_name: 'Dog Drive',
    landing_subtitle: 'Find the perfect match for your pet. Connect with walkers, sitters, and new friends.',
    choose_lang: 'Choose your language',
    login_title: 'Welcome back!',
    email_label: 'Email or Username',
    password_label: 'Password',
    forgot_pass: 'Forgot password?',
    enter_btn: 'Enter',
    or_continue: 'Or continue with',
    no_account: "Don't have an account?",
    signup_action: 'Sign up',
    onboarding_title: 'Welcome to Dog Drive!',
    onboarding_sub: 'Select your profile type to get started.',
    owner: 'Pet Owner',
    walker: 'Dog Walker',
    boarding: 'Pet Boarding',
    petshop: 'Pet Shop',
    grooming: 'Grooming',
    shop_function: 'Sell Products',
    email_placeholder: 'ex: doglover@email.com',
    password_placeholder: 'Enter your password',
    login_subtitle: 'The perfect match for your pet',
    continue: 'Continue',
    match_tab: 'MATCH',
    services_tab: 'SERVICES',
    chat_tab: 'CHATS',
    help_tab: 'HELP',
    settings_title: 'Settings',
    edit_profile: 'Edit Profile',
    my_dogs: 'My Dogs',
    add_another_dog: 'Add another dog',
    save_changes: 'Save Changes',
    services_title: 'What does your dog need?',
    walking_cat: 'Dog Walking',
    boarding_cat: 'Boarding',
    grooming_cat: 'Grooming',
    vet_cat: 'Vet Services',
    marketplace_cat: 'Marketplace',
    find_walker: 'Find a Walker',
    nearby: 'Nearby',
    top_rated: 'Top Rated',
    lowest_price: 'Lowest Price',
    per_hour: '/hr',
    book: 'Book',
    total: 'Total',
    messages: 'Messages',
    conversations: 'Conversations',
    need_help: 'Need help?',
    call_police: 'Call Police',
    report_accident: 'Report Accident',
    get_started: 'Get Started',
    select_language: 'Select language',
    vet_clinic: 'Veterinary Clinic',
    grooming_shop: 'Grooming Shop / Pet Shop',
    business_type_title: 'Business Type',
    business_type_subtitle: 'Select the service your company offers.',
    select_country: 'Select Country',
    brazil: 'Brazil',
    europe: 'Europe',
    business: 'Business',
    pet_name: 'Pet Name',
    pet_age: 'Pet Age',
    pet_photo: 'Pet Photo',
    pet_traits: 'Pet Traits',
    pet_request: 'What are you looking for?',
    business_name: 'Business Name',
    tax_id_eu: 'Tax ID / VAT Number',
    business_address: 'Business Address',
    service_type: 'Service Types',
    walking: 'Walking',
    boarding_label: 'Boarding',
    doc_upload: 'Document Upload',
    address_label: 'Address',
    bank_title: 'Bank Details',
    pix_key: 'PIX Key / IBAN',
    experience_label: 'Experience / Bio',
    finish_btn: 'Finish',
  },
  es: {
    app_name: 'Dog Drive',
    landing_subtitle: 'Encuentra la pareja perfecta para tu mascota. Conéctate con paseadores y nuevos amigos.',
    choose_lang: 'Elige tu idioma',
    login_title: '¡Bienvenido de nuevo!',
    email_label: 'Email o Usuario',
    password_label: 'Contraseña',
    forgot_pass: '¿Olvidaste tu contraseña?',
    enter_btn: 'Entrar',
    or_continue: 'O continúa con',
    no_account: '¿No tienes cuenta?',
    signup_action: 'Regístrate',
    onboarding_title: '¡Bienvenido a Dog Drive!',
    onboarding_sub: 'Selecciona tu tipo de perfil para comenzar.',
    owner: 'Dueño de Mascota',
    walker: 'Paseador',
    boarding: 'Hospedaje',
    petshop: 'Petshop',
    grooming: 'Peluquería',
    shop_function: 'Vender Productos',
    email_placeholder: 'ej: amantedelos perros@email.com',
    password_placeholder: 'Ingresa tu contraseña',
    login_subtitle: 'El match perfecto para tu mascota',
    continue: 'Continuar',
    match_tab: 'MATCH',
    services_tab: 'SERVICIOS',
    chat_tab: 'CHATS',
    help_tab: 'AYUDA',
    settings_title: 'Configuración',
    edit_profile: 'Editar Perfil',
    my_dogs: 'Mis Perros',
    add_another_dog: 'Añadir otro perro',
    save_changes: 'Guardar Cambios',
    services_title: '¿Qué necesita tu perro?',
    walking_cat: 'Paseo',
    boarding_cat: 'Hospedaje',
    grooming_cat: 'Peluquería',
    vet_cat: 'Veterinario',
    marketplace_cat: 'Tienda',
    find_walker: 'Buscar Paseador',
    nearby: 'Cercanos',
    top_rated: 'Mejor Valorados',
    lowest_price: 'Precio Más Bajo',
    per_hour: '/hr',
    book: 'Reservar',
    total: 'Total',
    messages: 'Mensajes',
    conversations: 'Conversaciones',
    need_help: '¿Necesitas ayuda?',
    call_police: 'Llamar Policía',
    report_accident: 'Reportar Accidente',
    get_started: 'Comenzar',
    select_language: 'Seleccionar idioma',
    vet_clinic: 'Clínica Veterinaria',
    grooming_shop: 'Peluquería / Petshop',
    business_type_title: 'Tipo de Negocio',
    business_type_subtitle: 'Selecciona el servicio que ofrece tu empresa.',
    select_country: 'Seleccionar País',
    brazil: 'Brasil',
    europe: 'Europa',
    business: 'Empresa',
    pet_name: 'Nombre de la Mascota',
    pet_age: 'Edad de la Mascota',
    pet_photo: 'Foto de la Mascota',
    pet_traits: 'Rasgos de la Mascota',
    pet_request: '¿Qué estás buscando?',
    business_name: 'Nombre de la Empresa',
    tax_id_eu: 'NIF / CIF / VAT Number',
    business_address: 'Dirección Comercial',
    service_type: 'Tipos de Servicio',
    walking: 'Paseo',
    boarding_label: 'Hospedaje',
    doc_upload: 'Subir Documento',
    address_label: 'Dirección',
    bank_title: 'Datos Bancarios',
    pix_key: 'Clave PIX / IBAN',
    experience_label: 'Experiencia / Bio',
    finish_btn: 'Finalizar',
  },
  zh: {
    app_name: 'Dog Drive',
    landing_subtitle: '为您的宠物找到完美的伴侣。与遛狗者和新朋友联系。',
    choose_lang: '选择语言',
    login_title: '欢迎回来！',
    email_label: '邮箱或用户名',
    password_label: '密码',
    forgot_pass: '忘记密码？',
    enter_btn: '登录',
    or_continue: '或继续使用',
    no_account: '没有账户？',
    signup_action: '注册',
    onboarding_title: '欢迎来到 Dog Drive！',
    onboarding_sub: '选择您的个人资料类型开始。',
    owner: '狗主人',
    walker: '遛狗和寄养',
    business: '宠物服务',
    email_placeholder: '例如: doglover@email.com',
    password_placeholder: '输入密码',
    login_subtitle: '为您的宠物找到完美匹配',
    continue: '继续',
    match_tab: '匹配',
    services_tab: '服务',
    chat_tab: '聊天',
    help_tab: '帮助',
    settings_title: '设置',
    edit_profile: '编辑资料',
    my_dogs: '我的狗',
    add_another_dog: '添加另一只狗',
    save_changes: '保存更改',
    services_title: '您的狗需要什么？',
    walking_cat: '遛狗',
    boarding_cat: '寄养',
    grooming_cat: '美容',
    vet_cat: '兽医',
    marketplace_cat: '商店',
    find_walker: '寻找遛狗者',
    nearby: '附近',
    top_rated: '评分最高',
    lowest_price: '最低价格',
    per_hour: '/小时',
    book: '预订',
    total: '总计',
    messages: '消息',
    conversations: '对话',
    need_help: '需要帮助？',
    call_police: '报警',
    report_accident: '报告事故',
    get_started: '开始',
    select_language: '选择语言',
  },
  hi: {
    app_name: 'Dog Drive',
    landing_subtitle: 'अपने पालतू जानवर के लिए सही साथी खोजें। वॉकर और नए दोस्तों से जुड़ें।',
    choose_lang: 'अपनी भाषा चुनें',
    login_title: 'वापसी पर स्वागत है!',
    email_label: 'ईमेल या उपयोगकर्ता नाम',
    password_label: 'पासवर्ड',
    forgot_pass: 'पासवर्ड भूल गए?',
    enter_btn: 'प्रवेश करें',
    or_continue: 'या जारी रखें',
    no_account: 'खाता नहीं है?',
    signup_action: 'साइन अप करें',
    onboarding_title: 'Dog Drive में आपका स्वागत है!',
    onboarding_sub: 'शुरू करने के लिए अपना प्रोफ़ाइल प्रकार चुनें।',
    owner: 'कुत्ते का मालिक',
    walker: 'वॉकर और बोर्डिंग',
    business: 'पेट सेवाएं',
    email_placeholder: 'उदा: doglover@email.com',
    password_placeholder: 'पासवर्ड दर्ज करें',
    login_subtitle: 'आपके पालतू जानवर के लिए सही मैच',
    continue: 'जारी रखें',
    match_tab: 'मैच',
    services_tab: 'सेवाएं',
    chat_tab: 'चैट',
    help_tab: 'मदद',
    settings_title: 'सेटिंग्स',
    edit_profile: 'प्रोफ़ाइल संपादित करें',
    my_dogs: 'मेरे कुत्ते',
    add_another_dog: 'एक और कुत्ता जोड़ें',
    save_changes: 'परिवर्तन सहेजें',
    services_title: 'आपके कुत्ते को क्या चाहिए?',
    walking_cat: 'वॉकिंग',
    boarding_cat: 'बोर्डिंग',
    grooming_cat: 'ग्रूमिंग',
    vet_cat: 'पशु चिकित्सक',
    marketplace_cat: 'बाज़ार',
    find_walker: 'वॉकर खोजें',
    nearby: 'पास में',
    top_rated: 'शीर्ष रेटेड',
    lowest_price: 'सबसे कम कीमत',
    per_hour: '/घंटा',
    book: 'बुक करें',
    total: 'कुल',
    messages: 'संदेश',
    conversations: 'बातचीत',
    need_help: 'मदद चाहिए?',
    call_police: 'पुलिस को बुलाएं',
    report_accident: 'दुर्घटना की रिपोर्ट करें',
    get_started: 'शुरू करें',
    select_language: 'भाषा चुनें',
  },
  ar: {
    app_name: 'Dog Drive',
    landing_subtitle: 'ابحث عن الشريك المثالي لحيوانك الأليف. تواصل مع المشاة والأصدقاء الجدد.',
    choose_lang: 'اختر لغتك',
    login_title: 'مرحباً بعودتك!',
    email_label: 'البريد الإلكتروني أو اسم المستخدم',
    password_label: 'كلمة المرور',
    forgot_pass: 'نسيت كلمة المرور؟',
    enter_btn: 'دخول',
    or_continue: 'أو تابع مع',
    no_account: 'ليس لديك حساب؟',
    signup_action: 'إنشاء حساب',
    onboarding_title: 'مرحباً بك في Dog Drive!',
    onboarding_sub: 'اختر نوع ملفك الشخصي للبدء.',
    owner: 'صاحب الكلب',
    walker: 'مشاي وإيواء',
    business: 'خدمات الحيوانات',
    email_placeholder: 'مثال: doglover@email.com',
    password_placeholder: 'أدخل كلمة المرور',
    login_subtitle: 'التطابق المثالي لحيوانك الأليف',
    continue: 'متابعة',
    match_tab: 'تطابق',
    services_tab: 'خدمات',
    chat_tab: 'دردشة',
    help_tab: 'مساعدة',
    settings_title: 'الإعدادات',
    edit_profile: 'تعديل الملف الشخصي',
    my_dogs: 'كلابي',
    add_another_dog: 'إضافة كلب آخر',
    save_changes: 'حفظ التغييرات',
    services_title: 'ماذا يحتاج كلبك؟',
    walking_cat: 'المشي',
    boarding_cat: 'الإيواء',
    grooming_cat: 'العناية',
    vet_cat: 'طبيب بيطري',
    marketplace_cat: 'السوق',
    find_walker: 'البحث عن مشاي',
    nearby: 'قريب',
    top_rated: 'الأعلى تقييماً',
    lowest_price: 'أقل سعر',
    per_hour: '/ساعة',
    book: 'حجز',
    total: 'المجموع',
    messages: 'الرسائل',
    conversations: 'المحادثات',
    need_help: 'تحتاج مساعدة؟',
    call_police: 'اتصل بالشرطة',
    report_accident: 'الإبلاغ عن حادث',
    get_started: 'ابدأ',
    select_language: 'اختر اللغة',
  },
  fr: {
    app_name: 'Dog Drive',
    landing_subtitle: 'Trouvez le partenaire idéal pour votre animal. Connectez-vous avec des promeneurs et de nouveaux amis.',
    choose_lang: 'Choisissez votre langue',
    login_title: 'Bon retour!',
    email_label: 'Email ou Nom d\'utilisateur',
    password_label: 'Mot de passe',
    forgot_pass: 'Mot de passe oublié?',
    enter_btn: 'Entrer',
    or_continue: 'Ou continuez avec',
    no_account: 'Pas de compte?',
    signup_action: 'S\'inscrire',
    onboarding_title: 'Bienvenue sur Dog Drive!',
    onboarding_sub: 'Sélectionnez votre type de profil pour commencer.',
    owner: 'Propriétaire de chien',
    walker: 'Promeneur et Pension',
    business: 'Services animaliers',
    email_placeholder: 'ex: amoureux.chiens@email.com',
    password_placeholder: 'Entrez votre mot de passe',
    login_subtitle: 'Le match parfait pour votre animal',
    continue: 'Continuer',
    match_tab: 'MATCH',
    services_tab: 'SERVICES',
    chat_tab: 'CHATS',
    help_tab: 'AIDE',
    settings_title: 'Paramètres',
    edit_profile: 'Modifier le profil',
    my_dogs: 'Mes chiens',
    add_another_dog: 'Ajouter un autre chien',
    save_changes: 'Enregistrer',
    services_title: 'De quoi votre chien a-t-il besoin?',
    walking_cat: 'Promenade',
    boarding_cat: 'Pension',
    grooming_cat: 'Toilettage',
    vet_cat: 'Vétérinaire',
    marketplace_cat: 'Boutique',
    find_walker: 'Trouver un promeneur',
    nearby: 'À proximité',
    top_rated: 'Mieux notés',
    lowest_price: 'Prix le plus bas',
    per_hour: '/h',
    book: 'Réserver',
    total: 'Total',
    messages: 'Messages',
    conversations: 'Conversations',
    need_help: 'Besoin d\'aide?',
    call_police: 'Appeler la police',
    report_accident: 'Signaler un accident',
    get_started: 'Commencer',
    select_language: 'Sélectionner la langue',
  },
  ru: {
    app_name: 'Dog Drive',
    landing_subtitle: 'Найдите идеальную пару для вашего питомца. Свяжитесь с выгульщиками и новыми друзьями.',
    choose_lang: 'Выберите язык',
    login_title: 'С возвращением!',
    email_label: 'Email или имя пользователя',
    password_label: 'Пароль',
    forgot_pass: 'Забыли пароль?',
    enter_btn: 'Войти',
    or_continue: 'Или продолжите с',
    no_account: 'Нет аккаунта?',
    signup_action: 'Регистрация',
    onboarding_title: 'Добро пожаловать в Dog Drive!',
    onboarding_sub: 'Выберите тип вашего профиля, чтобы начать.',
    owner: 'Владелец собаки',
    walker: 'Выгульщик и передержка',
    business: 'Зоо услуги',
    email_placeholder: 'например: doglover@email.com',
    password_placeholder: 'Введите пароль',
    login_subtitle: 'Идеальная пара для вашего питомца',
    continue: 'Продолжить',
    match_tab: 'МАТЧ',
    services_tab: 'УСЛУГИ',
    chat_tab: 'ЧАТЫ',
    help_tab: 'ПОМОЩЬ',
    settings_title: 'Настройки',
    edit_profile: 'Редактировать профиль',
    my_dogs: 'Мои собаки',
    add_another_dog: 'Добавить собаку',
    save_changes: 'Сохранить',
    services_title: 'Что нужно вашей собаке?',
    walking_cat: 'Выгул',
    boarding_cat: 'Передержка',
    grooming_cat: 'Груминг',
    vet_cat: 'Ветеринар',
    marketplace_cat: 'Магазин',
    find_walker: 'Найти выгульщика',
    nearby: 'Рядом',
    top_rated: 'Лучшие',
    lowest_price: 'Дешевле',
    per_hour: '/час',
    book: 'Забронировать',
    total: 'Итого',
    messages: 'Сообщения',
    conversations: 'Беседы',
    need_help: 'Нужна помощь?',
    call_police: 'Вызвать полицию',
    report_accident: 'Сообщить об аварии',
    get_started: 'Начать',
    select_language: 'Выбрать язык',
  },
  ja: {
    app_name: 'Dog Drive',
    landing_subtitle: 'ペットにぴったりのパートナーを見つけましょう。ウォーカーや新しい友達とつながりましょう。',
    choose_lang: '言語を選択',
    login_title: 'おかえりなさい！',
    email_label: 'メールまたはユーザー名',
    password_label: 'パスワード',
    forgot_pass: 'パスワードをお忘れですか？',
    enter_btn: 'ログイン',
    or_continue: 'または続ける',
    no_account: 'アカウントがありませんか？',
    signup_action: '新規登録',
    onboarding_title: 'Dog Driveへようこそ！',
    onboarding_sub: 'プロフィールタイプを選択して開始してください。',
    owner: '犬の飼い主',
    walker: 'ウォーカー＆預かり',
    business: 'ペットサービス',
    email_placeholder: '例: doglover@email.com',
    password_placeholder: 'パスワードを入力',
    login_subtitle: 'ペットに最適なマッチ',
    continue: '続ける',
    match_tab: 'マッチ',
    services_tab: 'サービス',
    chat_tab: 'チャット',
    help_tab: 'ヘルプ',
    settings_title: '設定',
    edit_profile: 'プロフィール編集',
    my_dogs: 'マイドッグ',
    add_another_dog: '犬を追加',
    save_changes: '保存',
    services_title: 'あなたの犬には何が必要ですか？',
    walking_cat: '散歩',
    boarding_cat: '預かり',
    grooming_cat: 'グルーミング',
    vet_cat: '獣医',
    marketplace_cat: 'マーケット',
    find_walker: 'ウォーカーを探す',
    nearby: '近く',
    top_rated: '高評価',
    lowest_price: '最安値',
    per_hour: '/時間',
    book: '予約',
    total: '合計',
    messages: 'メッセージ',
    conversations: '会話',
    need_help: '助けが必要ですか？',
    call_police: '警察を呼ぶ',
    report_accident: '事故を報告',
    get_started: '始める',
    select_language: '言語を選択',
  },
  de: {
    app_name: 'Dog Drive',
    landing_subtitle: 'Finden Sie den perfekten Partner für Ihr Haustier. Verbinden Sie sich mit Gassigängern und neuen Freunden.',
    choose_lang: 'Sprache wählen',
    login_title: 'Willkommen zurück!',
    email_label: 'E-Mail oder Benutzername',
    password_label: 'Passwort',
    forgot_pass: 'Passwort vergessen?',
    enter_btn: 'Einloggen',
    or_continue: 'Oder weiter mit',
    no_account: 'Kein Konto?',
    signup_action: 'Registrieren',
    onboarding_title: 'Willkommen bei Dog Drive!',
    onboarding_sub: 'Wählen Sie Ihren Profiltyp, um zu beginnen.',
    owner: 'Hundebesitzer',
    walker: 'Gassigeher & Pension',
    business: 'Tier-Services',
    email_placeholder: 'z.B.: hundeliebhaber@email.com',
    password_placeholder: 'Passwort eingeben',
    login_subtitle: 'Das perfekte Match für Ihr Haustier',
    continue: 'Weiter',
    match_tab: 'MATCH',
    services_tab: 'DIENSTE',
    chat_tab: 'CHATS',
    help_tab: 'HILFE',
    settings_title: 'Einstellungen',
    edit_profile: 'Profil bearbeiten',
    my_dogs: 'Meine Hunde',
    add_another_dog: 'Hund hinzufügen',
    save_changes: 'Speichern',
    services_title: 'Was braucht Ihr Hund?',
    walking_cat: 'Gassi gehen',
    boarding_cat: 'Pension',
    grooming_cat: 'Pflege',
    vet_cat: 'Tierarzt',
    marketplace_cat: 'Markt',
    find_walker: 'Gassigeher finden',
    nearby: 'In der Nähe',
    top_rated: 'Bestbewertet',
    lowest_price: 'Günstigster Preis',
    per_hour: '/Std.',
    book: 'Buchen',
    total: 'Gesamt',
    messages: 'Nachrichten',
    conversations: 'Gespräche',
    need_help: 'Hilfe benötigt?',
    call_police: 'Polizei rufen',
    report_accident: 'Unfall melden',
    get_started: 'Loslegen',
    select_language: 'Sprache wählen',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('dog_drive_lang');
    if (saved && Object.keys(translations).includes(saved)) {
      return saved as Language;
    }

    // Auto-detect from browser
    const browserLang = navigator.language.split('-')[0];
    if (Object.keys(translations).includes(browserLang)) {
      return browserLang as Language;
    }

    return 'en'; // Default to English if not detected or not supported
  });

  useEffect(() => {
    localStorage.setItem('dog_drive_lang', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useTranslation must be used within a LanguageProvider');
  return context;
};
